# python train.py --config-file configs/pascal/step2.yaml --num-gpus 1

_BASE_: step0-R101.yaml
DATASETS:
  TASK: 5-3
  STEP: 1
  SHOT: 1
  iSHOT: 0
MODEL:
  META_ARCHITECTURE: "MaskFormer"    # POS / MMFormer  
  WEIGHTS: out/voc-R101/voc_5-3_1shot/step0/model_best.pth # change to your path
  MASK_FORMER:
    PSEUDO_LABEL: True
    NUM_EXTRA_QUERIES: 14
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 5.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
  # BACKBONE:
  #   FREEZE_AT: 5
  KD:
    ENABLE: True
    FEATURE_WEIGHT: 0.5
    MASK_WEIGHT: 0.01
    CLASS_WEIGHT: 0.01
    TEMPERATURE: 2.0
  CON:
    ENABLE: False
    # QUERY_WEIGHT: 0.05
    PIXEL_WEIGHT: 0.2
OUTPUT_DIR: ./out/test

SOLVER:
  IMS_PER_BATCH: 20
  TEST_IMS_PER_BATCH: 16
  MAX_ITER: 1000
  WEIGHT_DECAY: 0.05    # 0.05
  BASE_LR: 0.0001
  OPTIMIZER: "ADAMW"   # ADAMW
TEST:
  EVAL_PERIOD: 10                ########################
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4

